### ISSUE TITLE
Request: Support dark theme 

### ISSUE THREAD

**Issue by ballastcanary** [yildbs/obsidian-harada-method-plugin#3]
Currently, in dark theme the text is low contrast light grey on white
![image](https://user-images.githubusercontent.com/99626481/233849462-2f0381b9-9851-4156-bf15-dd9b0bc84f96.png)

**Comment by mthlvt** [comment]
+1 thanks

**Comment by mthlvt** [comment]
quick workaround: add something like this to your [css snippets](https://help.obsidian.md/Extending+Obsidian/CSS+snippets)
```css
#goal{
    background-color: rgb(163 200 235 / 100%);
    color: #000;
}
#keyplan{
    background-color: rgb(163 200 235 / 50%);
}
#action{
    background-color: rgb(0 0 0 / 0%);
}
```
